import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Poppins({
  display: "swap",
  weight: ["300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Dravora | Sistem Order",
  description: "Generated by Dravora.id",
  icons: {
    icon: "/dravora.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
