import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Poppins({
  display: "swap",
  weight: ["300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Dravora | Sistem Order",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
